"""UniquenessCheck — every source file is claimed by exactly one most-specific doc.

Implements Part VI ("Hierarchical Describes") of `Irminsul-reference.md`. Two
docs claiming the same files at the same specificity is an error (silent
duplication). A source file in a covered directory that no doc claims is an
error (silent omission): documentation that covers a directory covers its code. A child doc claiming a narrower glob wins over a
parent's broader claim — that's the most-specific-match rule, and it's what
lets `planner/INDEX.md` say `describes: [app/planner/**]` while
`planner/routing.md` adds `describes: [app/planner/routing/*.py]` without
either docking the other.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable
from pathlib import Path
from typing import ClassVar

from pathspec import GitIgnoreSpec

from irminsul.checks.base import Finding, FindingClass, Severity
from irminsul.checks.globs import walk_configured_source_files
from irminsul.config import IrminsulConfig
from irminsul.declared_tests import governed_as_test
from irminsul.docgraph import DocGraph, DocNode

# Files that are usually noise from a doc-coverage standpoint. Keeping the
# omission warning quiet here trades a tiny risk of missing a legit doc gap
# against the much larger annoyance of warning on every `__init__.py`.
#
# The test conventions used to be listed here too, as a second copy of what the language
# profiles already say. They were a copy that disagreed: `*_test.go` was missing, so a Go
# test correctly declared under `owns_tests:` was still reported as undocumented source,
# and an adopter doing exactly what `test-ownership` asks could not get a green run. The
# question "is this file answerable to the test policy instead" now has one answer, in
# `declared_tests.governed_as_test`.
OMISSION_SKIP = GitIgnoreSpec.from_lines(
    [
        "__init__.py",
        "__main__.py",
        "conftest.py",
        "_version.py",  # generated by hatch-vcs / setuptools-scm
        "*.pyi",
        "*.d.ts",
    ]
)


def omitted_from_source_ownership(display: str, config: IrminsulConfig | None) -> bool:
    """Whether `describes:` ownership is not this file's question.

    Either it is noise no doc should have to claim, or the test policy owns it — and in
    that case `test-ownership` is what asks who maintains it, so the two checks partition
    the managed files rather than both skipping some.
    """
    if OMISSION_SKIP.match_file(display):
        return True
    return config is not None and governed_as_test(display, config)


def specificity(pattern: str) -> tuple[int, int, int]:
    """Higher tuple = more specific. Compared lexicographically.

    Components:
    - count of literal (no-wildcard) path segments — exact paths beat globs
    - total path depth — deeper claims beat shallower
    - negated wildcard-character count — fewer wildcards beats more
    """
    parts = pattern.split("/")
    literal_segments = sum(1 for p in parts if "*" not in p and "?" not in p)
    depth = len(parts)
    wildcard_chars = sum(p.count("*") + p.count("?") for p in parts)
    return (literal_segments, depth, -wildcard_chars)


# One `describes` claim on a source file: (doc, pattern, specificity score).
Claim = tuple[DocNode, str, tuple[int, int, int]]

CODE_DUPLICATE_CLAIM = "uniqueness/duplicate-claim"
CODE_UNDOCUMENTED_FILE = "uniqueness/undocumented-file"
CODE_UNLINKED_OVERLAP = "uniqueness/unlinked-overlap"


def resolve_claims(graph: DocGraph, source_files: list[tuple[Path, str]]) -> dict[str, list[Claim]]:
    """Map each claimed source display path to its (doc, pattern, specificity) claims.

    This is the single claim-resolution routine shared by the uniqueness check,
    `irminsul list undocumented`, and the co-change enforcement — "who owns
    this file?" has exactly one answer.
    """
    claims_by_file: dict[str, list[Claim]] = defaultdict(list)
    displays = [display for _, display in source_files]
    for node in graph.nodes.values():
        for pattern in node.frontmatter.describes:
            spec = GitIgnoreSpec.from_lines([pattern])
            score = specificity(pattern)
            for display in spec.match_files(displays):
                claims_by_file[display].append((node, pattern, score))
    return claims_by_file


def most_specific_claims(claims: list[Claim]) -> list[Claim]:
    """The claims at the highest specificity score — the file's owning docs."""
    top_score = max(c[2] for c in claims)
    return [c for c in claims if c[2] == top_score]


class UniquenessCheck:
    name: ClassVar[str] = "uniqueness"
    default_severity: ClassVar[Severity] = Severity.error
    explanations: ClassVar[dict[str, str]] = {
        CODE_DUPLICATE_CLAIM: (
            "Two or more docs claim the same source file at the same specificity, which is "
            "silent duplication. Narrow one claim's `describes` glob, or remove it."
        ),
        CODE_UNDOCUMENTED_FILE: (
            "A source file sits in a doc-covered directory but no doc's `describes` claims "
            "it, so nothing in the tree is responsible for describing it. Add it to the "
            "`describes` of the doc that should own it, or write one for it. A directory "
            "counts as covered when it holds claimed code, or when it was added inside a "
            "directory that does. A repository with an adoption record does not need that "
            "guess: there, every managed file the record does not except needs an owner, "
            "wherever it sits."
        ),
        CODE_UNLINKED_OVERLAP: (
            "A doc's `describes` claims files that a broader claim in another doc also "
            "matches, and neither doc links the other, so a reader of one never finds the "
            "other and the two can describe the same code twice. Link them, or narrow the "
            "broader claim."
        ),
    }
    classes: ClassVar[dict[str, FindingClass]] = {
        CODE_DUPLICATE_CLAIM: FindingClass.certain,
        CODE_UNDOCUMENTED_FILE: FindingClass.certain,
        CODE_UNLINKED_OVERLAP: FindingClass.hint,
    }

    def run(self, graph: DocGraph) -> list[Finding]:
        if graph.config is None or graph.repo_root is None:
            return []

        source_files = walk_configured_source_files(graph.repo_root, graph.config).files

        claims_by_file = resolve_claims(graph, source_files)

        out: list[Finding] = []

        # Tie at most-specific level → silent duplication, error.
        for source_file, claims in claims_by_file.items():
            top_claims = most_specific_claims(claims)
            if len(top_claims) > 1:
                claim_descs = ", ".join(
                    f"{node.path.as_posix()} (`{pattern}`)" for node, pattern, _ in top_claims
                )
                out.append(
                    Finding(
                        check=self.name,
                        code=CODE_DUPLICATE_CLAIM,
                        severity=Severity.error,
                        path=Path(source_file),
                        message=(
                            f"source file '{source_file}' is claimed at the same "
                            f"specificity by: {claim_descs}"
                        ),
                    )
                )

        out.extend(self._unlinked_overlaps(graph, claims_by_file))

        # Covered directories: parents of every claimed file.
        covered_dirs = _covered_dirs(claims_by_file.keys())
        documented_dirs = _documented_dirs(claims_by_file.keys())

        # An adoption record answers "was this file already here?" from a list somebody
        # wrote, so the covered-directory guess is not needed and not used. Everything
        # the record does not name needs an owner, wherever it sits.
        debt = _recorded_debt(graph)
        # Omission: a file no doc claims, under a covered directory or — once the tree
        # has an adoption record — anywhere the record does not except.
        for _, display in source_files:
            source_file = display
            if source_file in claims_by_file:
                continue
            if debt is not None:
                if source_file in debt:
                    continue
            elif not _is_in_covered_dir(source_file, covered_dirs, documented_dirs):
                continue
            if omitted_from_source_ownership(source_file, graph.config):
                continue
            out.append(
                Finding(
                    check=self.name,
                    code=CODE_UNDOCUMENTED_FILE,
                    severity=Severity.error,
                    path=Path(source_file),
                    message=(
                        f"source file '{source_file}' lives in a doc-covered "
                        "directory but no doc claims it"
                    ),
                    suggestion=(
                        f"run `irminsul context {source_file}` to find the nearest owning "
                        "doc and add the file to its `describes`, or write a doc for it "
                        "with `irminsul new component`"
                    ),
                    data={"problem": "undocumented-file", "file": source_file},
                )
            )

        return out

    def _unlinked_overlaps(
        self, graph: DocGraph, claims_by_file: dict[str, list[Claim]]
    ) -> list[Finding]:
        files_by_pair: dict[tuple[str, str], list[str]] = defaultdict(list)
        for source_file, claims in claims_by_file.items():
            top = most_specific_claims(claims)
            if len(top) != 1:
                continue
            owner = top[0][0]
            for other in {node.id: node for node, _, _ in claims if node.id != owner.id}.values():
                if not _linked(graph, owner, other):
                    files_by_pair[(owner.id, other.id)].append(source_file)
        out: list[Finding] = []
        for (owner_id, other_id), files in sorted(files_by_pair.items()):
            owner, other = graph.nodes[owner_id], graph.nodes[other_id]
            files.sort()
            shown = f"'{files[0]}'" + (f" and {len(files) - 1} more" if len(files) > 1 else "")
            out.append(
                Finding(
                    check=self.name,
                    code=CODE_UNLINKED_OVERLAP,
                    severity=Severity.warning,
                    path=owner.path,
                    doc_id=owner.id,
                    message=(
                        f"claims {shown}, which {other.path.as_posix()} also describes, and "
                        "neither doc links the other"
                    ),
                    suggestion=f"link {other.path.as_posix()}, or narrow its claim",
                )
            )
        return out


def _linked(graph: DocGraph, first: DocNode, second: DocNode) -> bool:
    for source, target in ((first, second), (second, first)):
        if source.id in graph.inbound_strong.get(target.id, set()):
            return True
        if source.id in graph.inbound_weak.get(target.id, set()):
            return True
    return False


def _recorded_debt(graph: DocGraph) -> frozenset[str] | None:
    """The adoption record's excepted paths, or `None` when the tree has no record.

    `None` and an empty record mean different things and must not collapse: no record at
    all keeps the progressive covered-directory rule, while a record that has shrunk to
    nothing means every managed file is owned and the closed rule applies with no
    exceptions left to spend.

    An unreadable record, and a cross-repository entry no boundary could confirm, are both
    reported by the `adoption-record` pass rather than here. That pass runs outside
    `checks.enabled`, because the record grants exceptions to this check and to
    `test-ownership`, and a repository may enable either alone — reporting from whichever
    happened to be listed is how a project running only `test-ownership` honoured a record
    nothing had validated. Both ownership rules consume the same set and say nothing about
    the file it came from.
    """
    from irminsul.adoption import AdoptionError, load_record, record_path, verified_debt

    if graph.repo_root is None or graph.config is None:
        return None
    path = record_path(graph.repo_root, graph.config)
    if not path.is_file():
        return None
    try:
        record = load_record(path)
    except AdoptionError:
        return None
    return verified_debt(graph.repo_root, graph.config, record, graph.source_map)[0]


def _covered_dirs(claimed_files: Iterable[str]) -> set[str]:
    """Every directory that has at least one claimed file under it (at any
    depth)."""
    dirs: set[str] = set()
    for f in claimed_files:
        parent = str(Path(f).parent.as_posix())
        while parent and parent != ".":
            dirs.add(parent)
            parent = str(Path(parent).parent.as_posix())
            if parent == ".":
                break
    return dirs


def _documented_dirs(claimed_files: Iterable[str]) -> set[str]:
    """The directories that hold a claimed file directly, not merely somewhere below.

    The repository root is excluded for the same reason `_covered_dirs` excludes it:
    every path's `parents` ends at `.`, so admitting it would make one claim on a
    root-level file — `main.go`, `setup.py` — cover the entire tree.
    """
    return {parent for f in claimed_files if (parent := Path(f).parent.as_posix()) != "."}


def _is_in_covered_dir(source_file: str, covered: set[str], documented: set[str]) -> bool:
    """Whether the omission of `source_file` is worth reporting.

    Its own directory holding claimed code is the original rule. A new directory added
    *inside* one that holds claimed code counts too: `src/pkg/newthing/mod.py` used to
    sit under no covered directory of its own, so nothing ever asked which doc describes
    it, however well documented `src/pkg` was. A sibling tree nobody has started
    documenting still does not count, so adopting a brownfield repo one directory at a
    time stays possible.
    """
    parent = Path(source_file).parent
    if parent.as_posix() in covered:
        return True
    return any(directory.as_posix() in documented for directory in parent.parents)
