"""Generate reference docs for Irminsul's code-derived documentation surfaces."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from irminsul.config import IrminsulConfig

GENERATED_COMMENT = "<!-- generated by irminsul regen --language=docs-surfaces -->"


@dataclass(frozen=True)
class GeneratedSurface:
    filename: str
    content: str


def expected_surfaces() -> list[GeneratedSurface]:
    return [
        GeneratedSurface("frontmatter-fields.md", render_frontmatter_fields()),
        GeneratedSurface("cli-commands.md", render_cli_commands()),
        GeneratedSurface("check-registries.md", render_check_registries()),
    ]


def surface_by_filename(filename: str) -> GeneratedSurface | None:
    if filename == "frontmatter-fields.md":
        return GeneratedSurface(filename, render_frontmatter_fields())
    if filename == "cli-commands.md":
        return GeneratedSurface(filename, render_cli_commands())
    if filename == "check-registries.md":
        return GeneratedSurface(filename, render_check_registries())
    return None


def regen_doc_surfaces(repo_root: Path, config: IrminsulConfig) -> list[Path]:
    """Write generated docs under docs/40-reference/."""
    out_dir = repo_root / config.paths.docs_root / "40-reference"
    written: list[Path] = []
    for surface in expected_surfaces():
        dest = out_dir / surface.filename
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(surface.content, encoding="utf-8")
        written.append(dest)
    return written


def render_frontmatter_fields() -> str:
    from irminsul.frontmatter import DocFrontmatter

    rows: list[tuple[str, str]] = []
    for name, field in DocFrontmatter.model_fields.items():
        required = "yes" if field.is_required() else "no"
        rows.append((name, required))

    return _document(
        doc_id="frontmatter-fields",
        title="Frontmatter Fields",
        body=[
            "# Frontmatter Fields",
            "",
            GENERATED_COMMENT,
            "",
            "| Field | Required |",
            "|-------|----------|",
            *_rows(rows),
            "",
        ],
    )


def render_cli_commands() -> str:
    rows = _cli_rows()
    return _document(
        doc_id="cli-commands",
        title="CLI Commands",
        body=[
            "# CLI Commands",
            "",
            GENERATED_COMMENT,
            "",
            "| Command | Kind |",
            "|---------|------|",
            *_rows(rows),
            "",
        ],
    )


def render_check_registries() -> str:
    from irminsul.checks import HARD_REGISTRY, LLM_REGISTRY, SOFT_REGISTRY

    rows: list[tuple[str, str]] = [
        *[("hard", name) for name in HARD_REGISTRY],
        *[("soft", name) for name in SOFT_REGISTRY],
        *[("llm", name) for name in LLM_REGISTRY],
    ]
    return _document(
        doc_id="check-registries",
        title="Check Registries",
        body=[
            "# Check Registries",
            "",
            GENERATED_COMMENT,
            "",
            "| Registry | Check |",
            "|----------|-------|",
            *_rows(rows),
            "",
        ],
    )


def _document(*, doc_id: str, title: str, body: list[str]) -> str:
    frontmatter = [
        "---",
        f"id: {doc_id}",
        f'title: "{title}"',
        "audience: reference",
        "tier: 1",
        "status: stable",
        "describes: []",
        "---",
        "",
    ]
    return "\n".join([*frontmatter, *body])


def _rows(rows: Iterable[tuple[str, str]]) -> list[str]:
    return [f"| `{left}` | {right} |" for left, right in rows]


def _cli_rows() -> list[tuple[str, str]]:
    from typer.main import get_command

    from irminsul.cli import app

    root = cast(Any, get_command(app))
    rows: list[tuple[str, str]] = []
    for name, command in sorted(root.commands.items()):
        children = getattr(command, "commands", None)
        if isinstance(children, dict):
            rows.append((name, "group"))
            rows.extend(_cli_child_rows(name, children))
        else:
            rows.append((name, "command"))
    return rows


def _cli_child_rows(prefix: str, commands: dict[str, object]) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for name, command in sorted(commands.items()):
        full_name = f"{prefix} {name}"
        children = getattr(command, "commands", None)
        if isinstance(children, dict):
            rows.append((full_name, "group"))
            rows.extend(_cli_child_rows(full_name, children))
        else:
            rows.append((full_name, "command"))
    return rows
