"""`irminsul regen --language=typescript` — write TypeScript reference stubs."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from irminsul.config import IrminsulConfig

_STUB_TEMPLATE = """\
---
id: {doc_id}
title: "{title}"
audience: reference
tier: 1
status: draft
---

# {title}

<!-- generated by irminsul regen --language=typescript -->
"""


class TypeScriptRegenError(RuntimeError):
    pass


def regen_typescript(
    repo_root: Path,
    config: IrminsulConfig,
    *,
    require_typedoc: bool = True,
) -> list[Path]:
    """Write TypeScript reference stubs under the configured output directory."""
    settings = config.regen.typescript
    if not settings.enabled:
        return []

    if require_typedoc:
        _ensure_typedoc(repo_root)

    out_dir = repo_root / settings.out_dir
    written: list[Path] = []
    seen_destinations: dict[Path, Path] = {}
    seen_doc_ids: dict[str, Path] = {}

    for root_str in config.paths.source_roots:
        src_root = repo_root / root_str
        if not src_root.is_dir():
            continue
        candidates = sorted([*src_root.rglob("*.ts"), *src_root.rglob("*.tsx")])
        for ts_file in candidates:
            if _should_skip(ts_file):
                continue
            rel = ts_file.relative_to(src_root)
            dest = out_dir / rel.with_suffix(".md")
            module_path = "/".join(rel.with_suffix("").parts)
            doc_id = "-".join(rel.with_suffix("").parts)
            _check_collision(
                source=ts_file,
                destination=dest,
                doc_id=doc_id,
                seen_destinations=seen_destinations,
                seen_doc_ids=seen_doc_ids,
            )
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(
                _STUB_TEMPLATE.format(doc_id=doc_id, title=module_path),
                encoding="utf-8",
            )
            written.append(dest)

    return written


def _check_collision(
    *,
    source: Path,
    destination: Path,
    doc_id: str,
    seen_destinations: dict[Path, Path],
    seen_doc_ids: dict[str, Path],
) -> None:
    prior_destination_source = seen_destinations.get(destination)
    if prior_destination_source is not None:
        raise TypeScriptRegenError(
            "TypeScript reference regen collision: "
            f"{source.as_posix()} and {prior_destination_source.as_posix()} "
            f"both map to {destination.as_posix()}"
        )

    prior_doc_id_source = seen_doc_ids.get(doc_id)
    if prior_doc_id_source is not None:
        raise TypeScriptRegenError(
            "TypeScript reference regen collision: "
            f"{source.as_posix()} and {prior_doc_id_source.as_posix()} "
            f"both use doc id '{doc_id}'"
        )

    seen_destinations[destination] = source
    seen_doc_ids[doc_id] = source


def _ensure_typedoc(repo_root: Path) -> None:
    local_typedoc = (
        repo_root / "node_modules" / ".bin" / ("typedoc.cmd" if _is_windows() else "typedoc")
    )
    if local_typedoc.is_file():
        cmd = [str(local_typedoc), "--version"]
    elif shutil.which("npx") is not None:
        cmd = ["npx", "--no-install", "typedoc", "--version"]
    else:
        raise TypeScriptRegenError(_typedoc_help())

    try:
        subprocess.run(cmd, cwd=repo_root, check=True, capture_output=True, text=True, timeout=15)
    except (subprocess.SubprocessError, OSError) as exc:
        raise TypeScriptRegenError(_typedoc_help()) from exc


def _typedoc_help() -> str:
    return (
        "TypeScript reference regen requires Node.js and local TypeDoc.\n"
        "Install: npm install --save-dev typedoc\n"
        "Then re-run: irminsul regen --language=typescript"
    )


def _is_windows() -> bool:
    return Path("C:/").anchor != ""


def _should_skip(path: Path) -> bool:
    name = path.name
    return name.startswith("_") or name.endswith(".d.ts") or name.endswith(".test.ts")
